<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UseMaui>true</UseMaui>
		<RootNamespace>Honu.Maui.Wizard.Tests</RootNamespace>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<Import Project="..\..\targets\default.targets" />

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Honu.Maui.Wizard\Honu.Maui.Wizard.csproj" />
	</ItemGroup>

</Project>
